MYSQL_CONFIG:
  name: "test"
  type: "mysql"
  host: 'sql_test'
  port: 3306
  username: demo_user
  password: 123456
  database: test
  entities: "mysql" 
  synchronize: true

#redis配置
#192.168.137.1
REDIS_CONFIG:
  REDIS_HOST: redis_demo  
  REDIS_PORT: 6379
  REDIS_DB:  0
  REDIS_PASSPORT: 123456

